services:
  nginx:
    image: nginx:1.27-alpine
    container_name: nginx_server
    ports:
      - "8080:80"
    volumes:
      - ./www:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  php:
    image: php:8.2-fpm-alpine
    container_name: php_fpm
    volumes:
      - ./www:/var/www/html
