services:
  nginx:
    image: nginx:latest
    container_name: nginx_server
    ports:
      - "8080:80"
    volumes:
      - ./www:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  php:
    image: danieldevop/php-para-glpi:8.2-fpm
    container_name: php_fpm
    volumes:
      - ./www:/var/www/html
